[dependencies]
chrono = '0.4.7'
rand = '0.7.0'
rql = '0.4.0'
serde = '1.0.98'
serde_derive = '1.0.98'
serde_yaml = '0.8.9'
serenity = '0.6.3'

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'discord_bot'
version = '0.1.0'
